# Generated by Django 2.0.5 on 2018-07-26 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novel', '0007_auto_20180720_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Novel', verbose_name='书编')),
            ],
            options={
                'verbose_name': '书架',
                'verbose_name_plural': '书架',
            },
        ),
        migrations.CreateModel(
            name='BookshelfGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20, verbose_name='组名')),
            ],
            options={
                'verbose_name': '书架组',
                'verbose_name_plural': '书架组',
            },
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='shelf_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.BookshelfGroup', verbose_name='分组'),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
