# Generated by Django 2.0.5 on 2018-07-26 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshelf',
            old_name='shelf_group',
            new_name='shelfgroup',
        ),
    ]
