# Generated by Django 2.0.5 on 2018-07-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_bookshelf_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
