# Generated by Django 2.0.5 on 2018-07-26 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_bookshelf_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='bookmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Chapter', verbose_name='书签'),
        ),
    ]
