# Generated by Django 2.0.5 on 2018-07-26 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0007_auto_20180720_0837'),
        ('bookshelf', '0005_auto_20180726_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddShelfNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0, verbose_name='加入书架数量')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Novel', verbose_name='书编')),
            ],
            options={
                'verbose_name': '加入书架数量',
                'verbose_name_plural': '加入书架数量',
            },
        ),
    ]
