# Generated by Django 2.0.5 on 2018-08-01 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0007_bookshelf_update_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='update_chapter',
        ),
    ]
