# Generated by Django 2.0.5 on 2018-07-26 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novel', '0007_auto_20180720_0837'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_num', models.IntegerField(default=0, verbose_name='投票数')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='投票时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Novel', verbose_name='书编')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '投票信息',
                'verbose_name_plural': '投票信息',
            },
        ),
        migrations.CreateModel(
            name='VoteTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_num', models.IntegerField(default=0, verbose_name='投票总数')),
                ('vote_time', models.DateTimeField(auto_now=True, verbose_name='投票时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '投票时间',
                'verbose_name_plural': '投票时间',
            },
        ),
        migrations.CreateModel(
            name='VoteTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.IntegerField(default=0, verbose_name='投票总数')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Novel', verbose_name='书编')),
            ],
            options={
                'verbose_name': '投票总数',
                'verbose_name_plural': '投票总数',
            },
        ),
    ]
