# Generated by Django 2.0.5 on 2018-07-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_auto_20180711_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='id_book',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='书编'),
        ),
    ]
