# Generated by Django 2.0.5 on 2018-07-20 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0005_chapter_insert_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='book',
            new_name='novel',
        ),
    ]
