# Generated by Django 2.0.5 on 2018-07-20 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0006_auto_20180720_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='novel',
            new_name='book',
        ),
    ]
