# Generated by Django 2.0.5 on 2018-07-23 07:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('readStatistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readrecord',
            name='read_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 7, 22, 33, 263660, tzinfo=utc), verbose_name='阅读时间'),
        ),
    ]
