# Generated by Django 2.0.5 on 2018-07-23 07:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('readStatistics', '0002_auto_20180723_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readrecord',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='readrecord',
            old_name='chapter_id',
            new_name='chapter',
        ),
        migrations.AlterField(
            model_name='readrecord',
            name='read_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 7, 51, 35, 131290, tzinfo=utc), verbose_name='阅读时间'),
        ),
    ]
