# Generated by Django 2.0.5 on 2018-07-26 02:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('readStatistics', '0003_auto_20180723_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readrecord',
            name='read_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 26, 1, 59, 54, 347370, tzinfo=utc), verbose_name='阅读时间'),
        ),
    ]
