# Generated by Django 2.0.5 on 2018-07-26 02:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('readStatistics', '0004_auto_20180726_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readrecord',
            name='read_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 26, 2, 2, 38, 477757, tzinfo=utc), verbose_name='阅读时间'),
        ),
    ]
