# Generated by Django 2.0.5 on 2018-07-26 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('readStatistics', '0015_auto_20180726_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readrecord',
            name='read_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 26, 7, 5, 45, 244672, tzinfo=utc), verbose_name='阅读时间'),
        ),
    ]
