# Generated by Django 2.0.5 on 2018-07-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readStatistics', '0016_auto_20180726_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readrecord',
            name='read_time',
            field=models.DateTimeField(auto_now=True, verbose_name='阅读时间'),
        ),
    ]
