# Generated by Django 2.0.5 on 2018-07-27 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novel', '0007_auto_20180720_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='描述')),
                ('report_time', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Novel', verbose_name='书编')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Chapter', verbose_name='章节')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'ordering': ['-report_time'],
            },
        ),
    ]
