# Generated by Django 2.0.5 on 2018-07-27 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporterror', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='描述')),
                ('report_time', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'ordering': ['-report_time'],
            },
        ),
        migrations.RemoveField(
            model_name='reporterror',
            name='book',
        ),
        migrations.RemoveField(
            model_name='reporterror',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='reporterror',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReportError',
        ),
    ]
