# Generated by Django 2.0.5 on 2018-07-27 02:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporterror', '0002_auto_20180727_1005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NovelError',
            new_name='ReportError',
        ),
    ]
