# Generated by Django 2.0.5 on 2018-07-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporterror', '0003_auto_20180727_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporterror',
            name='description',
        ),
        migrations.AddField(
            model_name='reporterror',
            name='content',
            field=models.TextField(default=None, verbose_name='举报内容'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporterror',
            name='title',
            field=models.CharField(default=None, max_length=50, verbose_name='标题'),
            preserve_default=False,
        ),
    ]
